package com.xincon.ecps.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-04T19:27:03.661+08:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://service.ws.ecps.xincon.com/", name = "EbWsItemSersvice")
@XmlSeeAlso({ObjectFactory.class})
public interface EbWsItemSersvice {

    @WebMethod
    @RequestWrapper(localName = "publishItem", targetNamespace = "http://service.ws.ecps.xincon.com/", className = "com.xincon.ecps.stub.PublishItem")
    @ResponseWrapper(localName = "publishItemResponse", targetNamespace = "http://service.ws.ecps.xincon.com/", className = "com.xincon.ecps.stub.PublishItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String publishItem(

            @WebParam(name = "arg0", targetNamespace = "")
                    Long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );
}
