package com.xincon.ecps.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-04T19:27:03.706+08:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "EbWsItemSersviceService",
                  wsdlLocation = "http://localhost:8083/services/publishItem?wsdl",
                  targetNamespace = "http://service.ws.ecps.xincon.com/")
public class EbWsItemSersviceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.ecps.xincon.com/", "EbWsItemSersviceService");
    public final static QName EbWsItemSersvicePort = new QName("http://service.ws.ecps.xincon.com/", "EbWsItemSersvicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8083/services/publishItem?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EbWsItemSersviceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8083/services/publishItem?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EbWsItemSersviceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EbWsItemSersviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EbWsItemSersviceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EbWsItemSersviceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EbWsItemSersviceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EbWsItemSersviceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EbWsItemSersvice
     */
    @WebEndpoint(name = "EbWsItemSersvicePort")
    public EbWsItemSersvice getEbWsItemSersvicePort() {
        return super.getPort(EbWsItemSersvicePort, EbWsItemSersvice.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EbWsItemSersvice
     */
    @WebEndpoint(name = "EbWsItemSersvicePort")
    public EbWsItemSersvice getEbWsItemSersvicePort(WebServiceFeature... features) {
        return super.getPort(EbWsItemSersvicePort, EbWsItemSersvice.class, features);
    }

}
